### ISSUE TITLE
Powerable Custom Blocks

### ISSUE THREAD

**Issue by funkychicken493** [Hydroxycobalamin/BlockArchitect#5]
### I confirm that...

- [X] I checked the issues page for similar issues. This Feature request won't be a duplicate.
- [X] I made sure that this feature does not exist yet by asking on the Discord or reading the Wiki.

### Description

The ability to make a custom block powerable (like the base/material of the block being a noteblock) would open many possibilities for custom redstone machinery. You could designate a block as "powerable" in the item flags then give it a task to run when it is powered. For example, if I wanted to make a custom speaker block which plays a ding sound effect when it is activated, then I could say that the block is powerable and then give in a task to inject which makes the ding sound. I think this could be reasonably implemented using an already existing redstone block, like a piston or noteblock, turning off the vanilla behaviors, and then giving it the custom properties to be handled.

**Comment by Hydroxycobalamin** [comment]
You can already do that by listening to the relevant event and check if the location that got powered has the flag `custom_block`. If it does, you can get the item from the DisplayEntity via flag `custom_block.entity` and the `EntityTag.item` tag and then do whatever you want.

I still wonder if I should add custom events for an easier integration though.

**Comment by funkychicken493** [comment]
Custom events would be very useful. I am planning to use something like this for custom redstone traps.

**Comment by Hydroxycobalamin** [comment]
Added an custom event for switchable materials with the id `blockarchitect_block_switched`.

Following context tags are available:
 
`<context.location>`, which returns a LocationTag of the custom block, 
`<context.switched>`, which returns if the block was switched or not.
`<context.blockarchitect_id>` which returns the item script name of the block.

This event is cancellable.
