### ISSUE TITLE
Built-In World Generation Features

### ISSUE THREAD

**Issue by funkychicken493** [Hydroxycobalamin/BlockArchitect#6]
### I confirm that...

- [X] I checked the issues page for similar issues. This Feature request won't be a duplicate.
- [X] I made sure that this feature does not exist yet by asking on the Discord or reading the Wiki.

### Description

The ability to have custom blocks generate (like ores or other features) would be incredibly useful for adding new ores. I specifically would like this for ores and other underground blocks. You should be able to specify things like y level min and max, vein size, chance to generate a vein, and how many veins per chunk (randomized). General settings for what vanilla ores use. This would, of course, use the chunk generation event and find a block to seed the vein in.

**Comment by Hydroxycobalamin** [comment]
This is out of scope for BlockArchitect. You can make use of `BlockArchitect_create_custom_block` to spawn them in your generator.
