### ISSUE TITLE
Slab support

### ISSUE THREAD

**Issue by RealDairyKing** [Hydroxycobalamin/BlockArchitect#9]
### I confirm that...

- [X] I checked the issues page for similar issues. This Feature request won't be a duplicate.
- [X] I made sure that this feature does not exist yet by asking on the Discord or reading the Wiki.

### Description

1. It would be nice to add custom slabs
2. Simply create slab blocks
3. I can already create slab blocks, they are just a little touchy, if you place two on top of each other it snaps to the bottom one and creates a "ghost" block that cannot be deleted and you can walk through it.

**Comment by Hydroxycobalamin** [comment]
Added in e3e1bb4.
